[mypy-django_ratelimit.*]
ignore_missing_imports = True
[mypy-decouple]
ignore_missing_imports = True
[mypy-honeypot.*]
ignore_missing_imports = True
[mypy-phonenumber_field.*]
ignore_missing_imports = True
